TwiSen/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TwiSenApp.urls')),
]

TwiSenApp/urls.py
from . import views
from django.urls import path

app_name = "TwiSenApp"

urlpatterns = [
    path('', views.index, name='index'),
    path("searchbyuname/", views.search_by_uname, name='searchbyuname'),
    path("searchbyhtag/", views.search_by_htag, name='searchbyhtag'),
    path("sentimentanalysis/", views.sentiment_analysis_of_tweets, name='sentimentanalysis'),
    path("savetocsv/", views.save_to_csv, name='savetocsv'),
]

TwiSenApp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    usernameorhashtag = models.CharField(max_length=200)
    since = models.DateField(null=True)


class Tweet(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    tweet_text = models.TextField()
    tweet_id = models.IntegerField()
    tweet_length = models.IntegerField()
    tweet_created_at = models.DateTimeField()
    tweet_source = models.CharField(max_length=200)
    tweet_favorite_count = models.IntegerField()
    tweet_retweet_count = models.IntegerField()
    tweet_location = models.CharField(max_length=255)

TwiSenApp/forms.py
from django import forms


class SearchFormUsername(forms.Form):
    username = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'class':'form-control row-style', 'placeholder':'Search for username here...'}))
    number_of_tweets = forms.IntegerField(label='', required=True, widget=forms.NumberInput(attrs={'class': 'form-control mt-3', 'placeholder': 'Number Of Tweets'}))

class SearchFormHashtag(forms.Form):
    search_hashtag = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'class':'form-control row-style', 'placeholder':'Search for hashtags here...'}))
    number_of_tweets = forms.IntegerField(label='', required=True, widget=forms.NumberInput(attrs={'class':'form-control mt-3', 'placeholder':'Number Of Tweets'}))
    date = forms.DateField(label='', required=False, widget=forms.DateInput(attrs={'type': 'date', 'class':'form-control mt-3'}))


class CSVFileForm(forms.Form):
    filename = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'class':'form-control row-style', 'placeholder':'Enter file name without file extension...'}))

TwiSenApp/views.py
from django.shortcuts import render
from textblob import TextBlob

from . import forms, models
from tweepy import API, Cursor, OAuthHandler
import numpy as np
import pandas as pd
import datetime
import csv
import os
import re


# Create your views here.


def index(request):
    return render(request, 'TwiSenApp/index.html')


def search_by_uname(request):
    form = forms.SearchFormUsername()
    tweets = []
    if request.method == 'POST':
        form = forms.SearchFormUsername(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            number_of_tweets = form.cleaned_data['number_of_tweets']
            fetcher = TweetsFetcher()
            fetched_tweets = fetcher.fetch_tweets_by_username(username, number_of_tweets)
            new_post = models.Post(usernameorhashtag=username, since=datetime.date.today())
            new_post.save()
            for tweet in fetched_tweets:
                data = fetcher.extract_data(tweet)
                new_tweet = models.Tweet(post_id=new_post, tweet_text=data[0], tweet_id=data[1], tweet_length=data[2],
                                         tweet_created_at=data[3], tweet_source=data[4], tweet_favorite_count=data[5],
                                         tweet_retweet_count=data[6], tweet_location=data[7])
                new_tweet.save()
                tweets.append(data)

    return render(request, 'TwiSenApp/searchbyuname.html', {'form':form, 'tweets':tweets})

def search_by_htag(request):
    form = forms.SearchFormHashtag()
    tweets = []
    if request.method == 'POST':
        form = forms.SearchFormHashtag(request.POST)
        if form.is_valid():
            hashtag = form.cleaned_data['search_hashtag']
            number_of_tweets = form.cleaned_data['number_of_tweets']
            date = str(form.cleaned_data['date'])

            fetcher = TweetsFetcher()
            fetched_tweets = fetcher.fetch_tweets_by_hashtag(hashtag, date, number_of_tweets)
            new_post = models.Post(usernameorhashtag=hashtag, since=date)
            new_post.save()
            for tweet in fetched_tweets:
                data = fetcher.extract_data(tweet)
                new_tweet = models.Tweet(post_id=new_post, tweet_text=data[0], tweet_id=data[1], tweet_length=data[2],
                                         tweet_created_at=data[3], tweet_source=data[4], tweet_favorite_count=data[5],
                                         tweet_retweet_count=data[6], tweet_location=data[7])


                new_tweet.save()
                tweets.append(data)

    return render(request, 'TwiSenApp/searchbyhtag.html', {'form':form, 'tweets':tweets})


def sentiment_analysis_of_tweets(request):
    tweet_id = models.Post.objects.all().order_by('-id')[0]
    tweets = models.Tweet.objects.filter(post_id=tweet_id)

    tweet_analyzer = SentimentAnalysis()

    df = tweet_analyzer.tweet_to_dataframe(tweets)
    df['sentiment'] = np.array([tweet_analyzer.analyze_sentiment(tweet) for tweet in df['tweets']])

    positive = 0
    negative = 0
    neutral = 0
    sentiments = [x for x in df['sentiment']]
    tweets = [x for x in df['tweets']]
    tweets_with_sentiments = []
    for x in range(len(sentiments)):
        tweets_with_sentiments.append([tweets[x], sentiments[x]])

    for i in sentiments:
        if i == 1:
            positive += 1
        elif i == -1:
            negative += 1
        else:
            neutral += 1
    return render(request, 'TwiSenApp/sentimentanalysisreport.html', {'positive':positive, 'negative':negative, 'neutral':neutral,
                                                                      'tweetswithsentiments':tweets_with_sentiments})

def save_to_csv(request):
    form = forms.CSVFileForm()
    error = ""
    if request.method == 'POST':
        form = forms.CSVFileForm(request.POST)

        if form.is_valid():
            filename = form.cleaned_data['filename']
            if '.' in filename:
                error = "Only enter the filename without extension"
            else:
                recent_data = models.Post.objects.all().order_by('-id')[0]
                data = [["text", "id", "length", "date", "source", "likes", "retweet", "location"]]
                rows = models.Tweet.objects.filter(post_id=recent_data.id)
                for row in rows:
                    text = row.tweet_text
                    id = row.tweet_id
                    length = row.tweet_length
                    date = row.tweet_created_at
                    source = row.tweet_source
                    likes = row.tweet_favorite_count
                    retweet = row.tweet_retweet_count
                    location = row.tweet_location
                    data.append([text, id, length, date, source, likes, retweet, location])

                desktop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')
                print(desktop+"\\"+filename+".csv")
                with open(desktop+"\\"+filename+".csv", "w", encoding="utf-8") as csvFile:
                    writer = csv.writer(csvFile)
                    writer.writerows(data)
                    csvFile.close()


    return render(request, 'TwiSenApp/savetocsv.html', {'form':form, 'error':error})

class TwitterCredentials():
    ACCESS_TOKEN = ""
    ACCESS_TOKEN_SECRET = ""
    CONSUMER_KEY = ""
    CONSUMER_SECRET = ""


class TwitterAuthenticator():
    def authenticate(self):
        auth = OAuthHandler(TwitterCredentials.CONSUMER_KEY, TwitterCredentials.CONSUMER_SECRET)
        auth.set_access_token(TwitterCredentials.ACCESS_TOKEN, TwitterCredentials.ACCESS_TOKEN_SECRET)
        return auth


class TweetsFetcher():
    def __init__(self):
        self.auth = TwitterAuthenticator().authenticate()
        self.twitter_client = API(self.auth)

    def fetch_tweets_by_username(self, username, num_tweets):
        tweets = []
        for tweet in Cursor(self.twitter_client.user_timeline, id=username).items(num_tweets):
            tweets.append(tweet)
        return tweets

    def fetch_tweets_by_hashtag(self, hashtag, date, num_tweets):
        tweets = []
        for tweet in Cursor(self.twitter_client.search, q=hashtag, lang="en", since=date).items(num_tweets):
            tweets.append(tweet)
        return tweets

    def extract_data(self, tweet):
        extracted_data = []
        extracted_data.append(tweet.text)
        extracted_data.append(tweet.id)
        extracted_data.append(len(tweet.text))
        extracted_data.append(tweet.created_at)
        extracted_data.append(tweet.source)
        extracted_data.append(tweet.favorite_count)
        extracted_data.append(tweet.retweet_count)
        if tweet.place != None:
            extracted_data.append(str(tweet.place.country + ", " + tweet.place.full_name))
        else:
            extracted_data.append("None")

        return extracted_data

class SentimentAnalysis():
    def tweet_to_dataframe(self, tweets):
        df = pd.DataFrame(data=[tweet.tweet_text for tweet in tweets], columns=['tweets'])
        df['id'] = np.array([tweet.tweet_id for tweet in tweets])
        df['len'] = np.array([tweet.tweet_length for tweet in tweets])
        df['date'] = np.array([tweet.tweet_created_at for tweet in tweets])
        df['source'] = np.array([tweet.tweet_source for tweet in tweets])
        df['likes'] = np.array([tweet.tweet_favorite_count for tweet in tweets])
        df['retweets'] = np.array([tweet.tweet_retweet_count for tweet in tweets])
        return df

    def clean_tweet(self, tweet):
        return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

    def analyze_sentiment(self, tweet):
        analysis = TextBlob(self.clean_tweet(tweet))

        if analysis.sentiment.polarity > 0:
            return 1
        elif analysis.sentiment.polarity == 0:
            return 0
        else:
            return -1

TwiSenApp/templates/TwiSenApp/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <!-- Font Awesome -->
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

      <!-- Custom CSS -->
      <link rel="stylesheet" href="{% static 'TwiSenApp/css/style.css' %}">

    <title>Twitter Sentiments</title>
  </head>
  <body>
  <div class="container">
      <nav class="navbar navbar-expand-lg navbar-primary">
          <a class="navbar-brand" href="{% url 'TwiSenApp:index' %}">
              <img src="{% static 'TwiSenApp/images/logo.png' %}" alt="logo" width="75" height="55">
              TWITTER SENTIMENTS
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
<!--            <ul class="navbar-nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="#">Home</a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="#">Features</a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="#">Pricing</a>-->
<!--              </li>-->
<!--            </ul>-->
          </div>
      </nav>
      <div>
          {% block content %}
          {% endblock %}
      </div>



  </div>
    <footer class="footer">
      <div class="container">
        <p class="text-center">Twitter Sentiments All rights reserved</p>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

TwiSenApp/templates/TwiSenApp/index.html
{% extends 'TwiSenApp/base.html' %}

{% block content %}
<div class="row row-style">
    <div class="col-md-6">
        <div class="card border-primary mb-3" style="max-width: 18rem;">
          <div class="card-header bg-primary text-light h4">Search tweets by USERNAME</div>
          <div class="card-body text-primary">
              <h5 class="card-title">You can search tweets of a specific twitter user by clicking the button below</h5>
              <a href="{% url 'TwiSenApp:searchbyuname' %}" class="btn btn-primary">Search <i class="fa fa-arrow-right"></i></a>
          </div>
        </div>
    </div>
    <div class="col-md-6">
       <div class="card border-primary mb-3" style="max-width: 18rem;">
          <div class="card-header bg-primary text-light h4">Search tweets by HASHTAG</div>
          <div class="card-body text-primary">
              <h5 class="card-title">You can search tweets of a specific hashtag by clicking the button below</h5>
              <a href="{% url 'TwiSenApp:searchbyhtag' %}" class="btn btn-primary">Search <i class="fa fa-arrow-right"></i></a>
          </div>
        </div>
    </div>
</div>
{% endblock %}

TwiSenApp/templates/TwiSenApp/savetocsv.html
{% extends 'TwiSenApp/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <div class="d-flex justify-content-center">
        <input type="submit" name="submit" value="Save" class="btn btn-primary mt-3">
        {% if error %}
            <span class="text-danger">{{error}}</span>
        {% endif %}
    </div>
</form>
{% endblock %}

TwiSenApp/templates/TwiSenApp/searchbyhtag.html
{% extends 'TwiSenApp/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <div class="d-flex justify-content-center">
        <input type="submit" name="submit" value="Search" class="btn btn-primary mt-3">
    </div>
</form>

{% if tweets %}
    <table class="table table-bordered table-striped row-style">
        <tr>
            <th>Text</th>
            <th>ID</th>
            <th>Length of tweet</th>
            <th>Date</th>
            <th>Source</th>
            <th>Likes</th>
            <th>Retweets</th>
            <th>Location</th>
        </tr>
    {% for tweet in tweets %}
        <tr>
            {% for column in tweet %}
                <td>{{column}}</td>
            {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <div class="d-flex justify-content-center">
        <a href="{% url 'TwiSenApp:sentimentanalysis' %}" class="btn btn-primary">Do sentiment analysis of tweets</a>
        &nbsp;
        <a href="{% url 'TwiSenApp:savetocsv' %}" class="btn btn-primary">Save the data in CSV file</a>
    </div>
{% endif %}
{% endblock %}

TwiSenApp/templates/TwiSenApp/searchbyuname.html
{% extends 'TwiSenApp/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <div class="d-flex justify-content-center">
        <input type="submit" name="submit" value="Search" class="btn btn-primary mt-3">
    </div>
</form>

{% if tweets %}
    <table class="table table-bordered table-striped row-style">
        <tr>
            <th>Text</th>
            <th>ID</th>
            <th>Length of tweet</th>
            <th>Date</th>
            <th>Source</th>
            <th>Likes</th>
            <th>Retweets</th>
            <th>Location</th>
        </tr>
    {% for tweet in tweets %}
         <tr>
             {% for column in tweet %}
                <td>{{column}}</td>
            {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <div class="d-flex justify-content-center">
        <a href="{% url 'TwiSenApp:sentimentanalysis' %}" class="btn btn-primary">Do sentiment analysis of tweets</a>
        &nbsp;
        <a href="{% url 'TwiSenApp:savetocsv' %}" class="btn btn-primary">Save the data in CSV file</a>
    </div>
{% endif %}
{% endblock %}

TwiSenApp/templates/TwiSenApp/sentimentanalysisreport.html
{% extends 'TwiSenApp/base.html' %}

{% block content %}
<div class="row-style">
    <p class="text-success text-center">{{positive}} people tweeted a positive review</p>
    <p class="text-danger text-center">{{negative}} people tweeted a negative review</p>
    <p class="text-warning text-center" >{{neutral}} people tweeted a neutral review</p>

    <table class="table table-striped">
        <tr>
            <th>Tweets</th>
            <th>Sentiments</th>
        </tr>
        {% for x in tweetswithsentiments %}
        <tr>
            {% for y in x%}
            <td>{{y}}</td>
            {% endfor %}
        </tr>
        {%  endfor %}
    </table>
</div>
{% endblock %}